

```{r}
# Hyothesis 2: Is the % of memory B cells after vaccination associated with the age of the patient and the type of vaccine received?
#reading dataset that is provided
library(tidyverse)
library(lubridate)
influenza <- read_csv("C:/Users/linad/Downloads/fluprint_export.csv")

#metadataset with only memory b cells and no category NULL vaccines, each patient is only 1 time in the dataset
#data provides the outcome to test the memory B cells, in % in parent
onlymemBcells <- influenza %>% filter(name == "memory B cells")
onlymemBcells <- onlymemBcells %>% select(donor_id, visit_age, vaccine, data) %>% filter(vaccine != "NULL")
onlymemBcells <- onlymemBcells %>% rename(memBcells = data)

# check that visit_age & memBcells is numeric
onlymemBcells$visit_age <- as.numeric(onlymemBcells$visit_age)
onlymemBcells$memBcells <- as.numeric(onlymemBcells$memBcells)

#visualization of age distribution with only mem b cells
onlymemBcells %>%
  ggplot(aes(x=visit_age)) +
  geom_histogram(binwidth = 4, fill = "skyblue", color = "black") +
  theme_classic()+
  labs(title = "Age distribution of patients with value for memory B cells", x="Age of patient at visit time", y="Number of patients")

#visualization of distribution of memory B cells
onlymemBcells %>%
  ggplot(aes(x=memBcells)) +
  geom_histogram() +
  theme_classic()+
  labs(title = "Distribution memBcells", x="% of memory B cells", y="Number of patients")

onlyvaccine3 <- onlymemBcells %>% filter(vaccine == 3)
#only 3 patients in our dataset with vaccine 3
onlyvaccine5 <- onlymemBcells %>% filter(vaccine == 5)
#only 3 patients in our dataset with vaccine 5

#after data exploration only 3 patients with vaccine 3 and 3 with vaccine 5, so excluding these types out our analysis
onlymemBcells <- onlymemBcells %>% filter(vaccine == 1 | vaccine ==2 | vaccine ==4)

#function to assign visit age to different age groups/categories
get_age_group <- function(age) {
  if (age >= 0 && age < 10.50) 
  {return("0-10")} 
  else 
    if (age >= 10.50 && age <= 15.49) {return("10-15")} 
  else 
    if (age >= 15.50 && age <= 20.49) {return("15-20")} 
  else 
    if (age >= 20.50 && age <= 25.49) {return("20-25")}
  else 
    if (age >= 25.50 && age <= 30.49) {return("26-30")}
  else {return("30+")}
}

# Add a new column "age_group" by applying the function 
onlymemBcells$age_group <- sapply(onlymemBcells$visit_age, get_age_group)

#count which donors were not assigned an age group
tellNULLmem <- onlymemBcells %>% filter(age_group == "NULL")

#boxplot for %memory B cells per age group (& colored with vaccine)
onlymemBcells %>%
  ggplot(aes(x=age_group, y=memBcells, color=vaccine))+
  geom_boxplot() +
  theme_classic() +
  labs(title = "Boxplot % memory B cells per age group", x="Age group", y="% memory B cells")


#Boxplot for vaccine type & mem B cells
onlymemBcells %>%
  ggplot(aes(x=vaccine, y=memBcells))+
  geom_boxplot() +
  theme_classic() +
  labs(title = "Boxplot % memory B cells per vaccine type", x="Vaccine", y="% memory B cells")

#testing normality in data with Shapiro-Wilk-test
model <- lm(memBcells ~ age_group * vaccine, data = onlymemBcells)
residuals <- resid(model)
shapiro.test(residuals)
# visualisation distibution confirming Shapiro-Wilk test
qqnorm(residuals)
qqline(residuals, col = "red")

# Data is not distributed normally, test transformations with Shapiro-Wilk test
model_trans <- lm(sqrt(memBcells) ~ age_group * vaccine, data = onlymemBcells)
trans_residuals<-resid(model_trans)
shapiro.test(trans_residuals)
#visualization of distibution after sqrt-transformation
qqnorm(trans_residuals)
qqline(trans_residuals, col = "red")
#Test and qq-plot confirm normality after transformation

#check assumption linearity
plot(model_trans, which = 1)
#no pattern is visible, data is linear

#check assumption of homoscedasticity
library(car)
leveneTest(sqrt(memBcells) ~ age_group * vaccine, data = onlymemBcells)

#2 way anova test
anova_result <- aov(sqrt(memBcells) ~ age_group * vaccine, data = onlymemBcells)
summary(anova_result)


#to check for estimated effects of independent variables.
model_interaction <- lm(sqrt(memBcells) ~ age_group * vaccine, data = onlymemBcells)
summary(model_interaction)
